openapi: 3.1.0
info:
  version: 1.0.0
  title: API для управління контактами та користувачами
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Цей API надає розширений функціонал для управління обліковими записами користувачів та їхніми особистими контактами. 
    Він включає функції реєстрації користувачів, автентифікації, скидання паролів та управління сесіями. 
    Користувачі можуть створювати, оновлювати, видаляти та отримувати контакти, фільтрувати їх за типом або статусом улюбленого, 
    а також завантажувати фотографії профілю, використовуючи безпечне хмарне зберігання.
tags:
  - name: Contacts
    description: Операції, пов'язані з контактами
  - name: Auth
    description: Операції, пов'язані з автентифікацією користувачів
servers:
  - url: https://nodejs-hw-mongodb-i55t.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: "../swagger/paths/contacts/{id}/get.yaml"
    patch:
      $ref: "../swagger/paths/contacts/{id}/patch.yaml"
    delete:
      $ref: "../swagger/paths/contacts/{id}/delete.yaml"
  /contacts:
    get:
      $ref: "../swagger/paths/contacts/get.yaml"
    post:
      $ref: "../swagger/paths/contacts/post.yaml"
  /auth/register:
    post:
      tags:
        - Auth
      summary: Реєстрація нового користувача
      operationId: registerUser
      requestBody:
        description: Дані для реєстрації
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "201":
          description: Успішна реєстрація
        "400":
          description: Невірні дані реєстрації
  /auth/login:
    post:
      tags:
        - Auth
      summary: Логін користувача
      operationId: loginUser
      requestBody:
        description: Дані для входу
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Успішний вхід
        "401":
          description: Невірні дані для входу
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: "../swagger/components/contact.yaml"
    UserRegistration:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
